server:
  port: 8023

jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: gantch-account-secret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24)
  tokenHead: Bearer  #JWT负载中拿到开头

secure:
  ignored:
    urls:
      - /swagger-ui.html
      - /swagger-resources/**
      - /swagger/**
      - /webjars/springfox-swagger-ui/**
      - /**/v2/api-docs
      - /api/v1/mobile/phoneRegister
      - /api/v1/mobile/phoneLogin
      - /druid/**
      - /actuator/**
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.ico

spring:
  profiles:
    active: dev

# 自定义redis key
redis:
  key:
    prefix:
      authCode: "portal:authCode:"
    expire:
      authCode: 90 # 验证码超期时间

logging:
  level:
    root: info
    com.gantch: debug
#    file: nbiot_log.log